make:
	./make_ssd
	clear
	./ssd_fuse -d /tmp/ssd
t1:
	bash test.sh test1
t2:
	bash test.sh test2
ct1:
	bash ctest.sh test1
ct2:
	bash ctest.sh test2
ct3:
	bash ctest.sh test3
ct4:
	bash ctest.sh test4
ct5:
	bash ctest.sh test5