#include <stdint.h>
#include "exception.h"
#include "thread.h" 
#include "io.h"
#include "mini_uart.h"
#include "timer.h"
#include "printf.h"
#include "utils.h"

int count = 0;

void enable_interrupt() { asm volatile("msr DAIFClr, 0xf"); }

void disable_interrupt() { asm volatile("msr DAIFSet, 0xf"); }

void sync_handler(uint64_t sp) { 
  // handles exception generated by user commadn
  // , for example 'svc'
  uint64_t spsr_el1, elr_el1, esr_el1;
  asm volatile("mrs %0, spsr_el1" : "=r"(spsr_el1));
  asm volatile("mrs %0, elr_el1" : "=r"(elr_el1));
  asm volatile("mrs %0, esr_el1" : "=r"(esr_el1));
  //print_s("SPSR_EL1: ");
  //print_h(spsr_el1);
  //print_s("\n");
  //print_s("ELR_EL1: ");
  //print_h(elr_el1); // return address of EL1 exception
  //print_s("\n");
  //print_s("ESR_EL1: "); 
  //print_h(esr_el1); // cause of the exception
  //print_s("\n\n");

  int sys_call_num;
    asm volatile("mov %0, x8" : "=r"(sys_call_num));
    trap_frame_t *trap_frame = (trap_frame_t *)sp;
  //printf("syscall num: %d\n", sys_call_num);

  if(sys_call_num == 0){ // int getpid()
      uint32_t pid = get_current()->pid;
      asm volatile("mov x0, %0" : "=r"(pid)); // function reture value
    }else if(sys_call_num == 1){ // uart_read(char buf[], size_t size)
      //printf("uart_read\n");
      char *str = (char *)(trap_frame->x[0]);
      uint32_t size = (uint32_t)(trap_frame->x[1]);
      //for(int i = 0; i<8; i++){
      //  printf("buffer size: %d\n", trap_frame->x[i]);
      //}
      //enable_uart_interrupt();
      //core_timer_enable(SCHEDULE_TVAL);
      
      //core_timer_disable();
      disable_uart_interrupt();
      
      core_timer_enable(SCHEDULE_TVAL);
      plan_next_interrupt_tval(SCHEDULE_TVAL);
      enable_interrupt();
      
      //disable_interrupt();
      //int a;
      //while(1){
      //  disable_interrupt();
      //  printf("waiting function: %d\n", a++);
      //  enable_interrupt();
      //  delay(100000000);
      //}01010110000000000000000000000000
      //size = uart_async_gets(str, size);
      size = uart_gets(str, size);
      //disable_uart_interrupt();
      //disable_interrupt();
      printf("str: %s, size: %d\n", str, size);
      trap_frame->x[0] = size;
      //printf("uart_end\n");
      
    }else if(sys_call_num == 2){ // uartread(char buf[], size_t size)
  
      char* str = (char*) trap_frame->x[0];
      //printf("str: %s\n\n", str);
      uint32_t size = (uint32_t)(trap_frame->x[1]);
      uart_write(str, size);  
    }
  //while(1){}
}

void lower_64_EL_sync_handler(uint64_t sp){
  
  // exception registor
  uint64_t spsr_el1, elr_el1, esr_el1;
  asm volatile("mrs %0, spsr_el1" : "=r"(spsr_el1));
  asm volatile("mrs %0, elr_el1" : "=r"(elr_el1));
  asm volatile("mrs %0, esr_el1" : "=r"(esr_el1));
  //print_s("ESR_EL1: "); 
  //print_h(esr_el1); // cause of the exception
  //print_s("\n\n");
  // https://developer.arm.com/documentation/ddi0595/2021-06/AArch64-Registers/ESR-EL1--Exception-Syndrome-Register--EL1-
  int ec = (esr_el1 >> 26) & 0x3f; // exception class
  //int iss = esr_el1 & ((1 << 25) - 1); // [24:0], instruction specific syndrome {svc <iss>}
  //printf("lower sync handler\n");
  if(ec == 0b010101){
    // according the lab spec, the number of the systme call is store in x8
    trap_frame_t *trap_frame = (trap_frame_t *)sp;
    int sys_call_num;
    asm volatile("mov %0, x8" : "=r"(sys_call_num));

    if(sys_call_num == 0){ // int getpid()
      uint32_t pid = get_current()->pid;
      asm volatile("mov x0, %0" : "=r"(pid)); // function reture value
    }else if(sys_call_num == 1){ // uart_read(char buf[], size_t size)
      printf("uart_read\n");
      char *str = (char *)(trap_frame->x[0]);
      uint32_t size = (uint32_t)(trap_frame->x[1]);
      //for(int i = 0; i<8; i++){
      //  printf("buffer size: %d\n", trap_frame->x[i]);
      //}
      //enable_uart_interrupt();
      //core_timer_enable(SCHEDULE_TVAL);
      
      //core_timer_disable();
      disable_uart_interrupt();
      
      core_timer_enable(SCHEDULE_TVAL);
      plan_next_interrupt_tval(SCHEDULE_TVAL);
      enable_interrupt();
      
      //disable_interrupt();
      //int a;
      //while(1){
      //  disable_interrupt();
      //  printf("waiting function: %d\n", a++);
      //  enable_interrupt();
      //  delay(100000000);
      //}01010110000000000000000000000000
      //size = uart_async_gets(str, size);
      size = uart_gets(str, size);
      //disable_uart_interrupt();
      //disable_interrupt();
      printf("str: %s, size: %d\n", str, size);
      trap_frame->x[0] = size;
      printf("uart_end\n");
      
    }else if(sys_call_num == 2){ // uart_write(char buf[], size_t size)
      //disable_uart_interrupt();
      char* str = (char*) trap_frame->x[0];
      uint32_t size = (uint32_t)(trap_frame->x[1]);
      uart_write(str, size);  
    }else if(sys_call_num == 3){
      print_s("exec called\r\n");
      //char *program_name = (char *)trap_frame->x[0];
      //const char **argv = (const char **)trap_frame->x[1];
      thread_create(exec);
      //exec();
    }else if(sys_call_num == 4){
      print_s("fork called\r\n");
      fork(sp);
    }else if(sys_call_num == 5){
      //print_s("exit called\r\n");
    }else if(sys_call_num == 6){
      print_s("mbox_call called\r\n");
    }else if(sys_call_num == 7){
      print_s("kill called\r\n");
    }else{
      print_s("unhandled system call number\r\n");
    }
  }
  //printf("out handler\n");
  //plan_next_interrupt_tval(SCHEDULE_TVAL);
  //enable_core_timer(SCHEDULE_TVAL);
  //core_timer_enable(SCHEDULE_TVAL);
  //enable_interrupt();
}

// user timer handler
void el0_to_el1_irq_handler() {
  disable_interrupt();
  uint32_t is_uart = (*IRQ_PENDING_1 & AUX_IRQ);
  uint32_t is_core_timer = (*CORE0_IRQ_SOURCE & CNTPNS_IRQ);
  //printf("is_core_timer: %d\n", is_core_timer);
  if (is_uart) {
    uart_handler();
    
  } else if(is_core_timer) {
    printf("user timer irq\n");
    //core_timer_handler(); 
    ////core_timer_enable(SCHEDULE_TVAL);
    ////plan_next_interrupt_tval(SCHEDULE_TVAL << 5);
    kill_zombies();
    handle_fork();
    //////schedule();
    ////plan_next_interrupt_sec(1);
    //plan_next_interrupt_tval(SCHEDULE_TVAL);
    //
    schedule();
  }
  
  enable_interrupt();
  //printf("done\n");
}

// kernel timer handler
uint64_t el1_to_el1_irq_handler(uint64_t sp) {

  disable_interrupt();
  uint32_t is_uart = (*IRQ_PENDING_1 & AUX_IRQ);
  uint32_t is_core_timer = (*CORE0_IRQ_SOURCE & CNTPNS_IRQ);
  //printf("kernel:is_core_timer: %d\n", is_core_timer);
  if (is_uart) {
    uart_handler();
  } else if(is_core_timer) {
    kill_zombies();
    handle_fork();
    ////schedule();
    //plan_next_interrupt_sec(1);
    plan_next_interrupt_tval(SCHEDULE_TVAL);
    
    schedule();
  }
  //plan_next_interrupt_tval(SCHEDULE_TVAL);
  enable_interrupt();
  return sp;
}


//void irq_handler2() {
//  disable_interrupt();
//  uint32_t is_uart = (*IRQ_PENDING_1 & AUX_IRQ);
//
//  if (is_uart) {
//    uart_handler();
//  } else {
//    print_s("irq_handler2!!!!");
//    core_timer_handler();
//  }
//  enable_interrupt();
//}

void default_handler() { print_s("===== default handler =====\n"); }